server:
  port: 2000

spring:
  application:
    name: YANG-CROWD-MYSQL
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/project_crowd?severTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1000/eureka/
    fetch-registry: true
    register-with-eureka: true
mybatis:
  mapper-locations: MemberPOMapper.xml

logging:
  level:
    com.yang.crowd.mapper: debug
    com.yang.crowd.test: debug